service:
  name: IIS-demo
  identifier: IISdemo
  orgIdentifier: default
  projectIdentifier: demo
  serviceDefinition:
    spec:
      artifacts:
        primary:
          primaryArtifactRef: nexus
          sources:
            - spec:
                connectorRef: IIS
                repository: IIS
                repositoryFormat: raw
                tagRegex: /*.zip
                digest: ""
                spec:
                  group: /
              identifier: nexus
              type: Nexus3Registry
    type: WinRm
